id: P3A4AB64A
initial_creation_type: input
source_metadata:
  title: Lamrim Series
  language: de
  description: Texts on the subject of the graduated path (lam rim), which was introduced
    to Tibet by Atiśa in his most important work Lamp for the Path of Awakening (Bodhipathapradīpa)
    and subsequently adopted by all schools of Tibetan Buddhism, especially the Kadam
    and Gelug.
  volume:
    28977b4427b64abe88b1a11fd5f64b34:
      title: The Lamp for the Path to Enlightenment
      parent: Advice
    9c82d1387c12480eb363bd34cd6d637e:
      title: 'A Precious Garland for the Supreme Path of the Three Types of Individual:
        The Root of Dakpo''s Four Dharmas'
      parent: Advice
    37e737fbfa6942d3b8708200daa0e07c:
      title: 'Sweet Nectar of the Supreme Vehicle: A Synopsis of the Stages of the
        Mahāyāna Path'
      parent: Advice
    eb91494f5af14abe9edfbf58a02a6a0d:
      title: 'The Essence of Nectar: Graduated Stages of the Path — Advice for Renunciant
        Meditators'
      parent: Advice
    64e679ff13234954b0cffe9632e79543:
      title: Three Principal Aspects of the Path
      parent: Advice
    bc30f152d7d04214b67ed9ce582d83d7:
      title: A Brief Commentary on the Twelve Stanzas (Including the Divisions of
        the Stages of the Path for Individuals of the Three Capacities)
      parent: Commentaries
    21282d4a7c85488ab1f0508e697bc4b1:
      title: 'A Few Words of Commentary to Clarify The Essence of Nectar: Graduated
        Stages of the Path—Advice for Renunciant Meditators'
      parent: Commentaries
    197e810e117345f79f1cdf0272841687:
      title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages
        of the Path Combined with Guru Yoga'
      parent: Guru Yoga
    f730309cc6dd484f847db102eefe4564:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    0ceb2a8794b94e44b3c97b2b2b020fbd:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T04:07:49.608257'
last_modified_at: '2022-03-01T04:07:49.608260'
